---
abstract: 'SVG::TT::Graph charts (in svg/png/gif/jpeg..) for your Catalyst application'
author:
  - 'Terence Monteiro <terencemo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-View-SVG-TT-Graph
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst::Action::RenderView: '0.01'
  Catalyst::Plugin::ConfigLoader: '0.23'
  Catalyst::Plugin::Static::Simple: '0.01'
  Catalyst::Runtime: '5.80001'
  FindBin: '1.42'
  Image::LibRSVG: '0.07'
  MIME::Types: '1.30'
  Moose: '1.09'
  SVG::TT::Graph: '0.21'
  Test::More: '0.94'
  Test::WWW::Mechanize::Catalyst: '0.52'
  namespace::autoclean: '0.09'
version: 0.0226
